clinicaalamos2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from apps.Cuenta import views as user_views
from apps.Secretaria import views as secretaria_views
from apps.Medico import views as medico_views
from apps.Paciente import views as paciente_views
from django.conf.urls import url
from apps.Cuenta.decorators import unauthenticated_user, allowed_users
from django.contrib.auth.decorators import login_required



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    url('especialidad/get_especialidades/$', secretaria_views.get_especialidades, name='get_especialidades'),
    url('especialidad/get_horas_no_disponibles/$', secretaria_views.get_horas_no_disponibles, name='get_horas_no_disponibles'),
    # url('especialidad/eliminar_cita/$', secretaria_views.eliminar_cita, name='eliminar_cita'),

    path('register/', user_views.registerPage, name="register"),
    path('login/', user_views.loginPage, name="login"),
    path('logout/', user_views.logoutUser, name="logout"),
    path('user/', user_views.logoutUser, name="user-page"),
    path('secretaria/agregar_cita', secretaria_views.Agregar_cita.as_view(), name="agregar_cita_secretaria"),
    path('secretaria/editar_cita/<str:pk>', secretaria_views.Modificar_cita.as_view(), name='editar_cita'),
    path('secretaria/eliminar_cita/<str:pk>', secretaria_views.Eliminar_cita.as_view(), name='eliminar_cita'),
    path('medico/lista_citas', medico_views.Lista_citas, name="lista_citas"),
    path('secretaria/lista_citas', secretaria_views.Lista_citas_secretaria.as_view(), name="lista_citas_secretaria"),
    path('paciente/agregar_cita', paciente_views.Agregar_cita.as_view(), name="agregar_cita_paciente"), 
    path('secretaria/lista_pagos/', login_required(login_url='login')(secretaria_views.lista_medicos_pagos) , name="lista_medicos_pagos"), 
    # 
    # path('secretaria/eliminarCita/<str:pk>', secretaria_views.eliminar_cita, name="eliminar_cita"),
]

apps/Cuenta/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from apps.Medico.models import Medico

TIPO_USUARIO = (
    ('paciente', 'Paciente'),
    ('secretaria', 'Secretaria'),
    ('medico', 'Médico'),
    ('dueno', 'Dueño')
)

class Usuario(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    rut = models.CharField(max_length=12, null=True)
    tipo = models.CharField(max_length=50, choices=TIPO_USUARIO)

    def __str__(self):
        return self.name


# class MedicoUser(models.Model):
#     user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
#     medico = models.ForeignKey(Medico, null=True, blank=True, on_delete=models.CASCADE)
#     phone = models.CharField(max_length=200, null=True)
#     email = models.CharField(max_length=200, null=True)
    
#     def __str__(self):
#         return self.name

# class Paciente(models.Model):
#     user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
#     name = models.CharField(max_length=200, null=True)
#     phone = models.CharField(max_length=200, null=True)
#     email = models.CharField(max_length=200, null=True)
    
#     def __str__(self):
#         return self.name

# class Dueno(models.Model):
#     user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
#     name = models.CharField(max_length=200, null=True)
#     phone = models.CharField(max_length=200, null=True)
#     email = models.CharField(max_length=200, null=True)
    
#     def __str__(self):
#         return self.name

apps/Medico/models.py
from django.db import models

# Create your models here.
class Especialidad(models.Model):
    nombre_especialidad = models.TextField()
    valor = models.IntegerField()

    def __str__(self):
        return self.nombre_especialidad

class Medico(models.Model):
    run_medico = models.TextField(primary_key=True)
    nombre_medico = models.TextField()
    especialidad = models.ForeignKey(Especialidad, null=True, blank=True, on_delete=models.CASCADE)


    def __str__(self):
        return self.nombre_medico
    

TIPO_PREVISION = (
    ('Fonasa', 'Fonasa'),
    ('Isapre', 'Isapre'),
    ('Ninguna', 'Ninguna'),
)

apps/Paciente/models.py
from django.db import models

# Create your models here.

apps/Secretaria/models.py
from django.db import models
from apps.Medico.models import TIPO_PREVISION,Medico,Especialidad
# Create your models here.

class CitaMedica(models.Model):
    run= models.TextField(primary_key=True)
    nombre_paciente = models.TextField()
    tipo_prevision = models.CharField(max_length=50, choices=TIPO_PREVISION)
    medico = models.ForeignKey(Medico, related_name='medico', null=True, blank=True, on_delete=models.CASCADE)
    fecha_cita =  models.DateField()
    hora_cita = models.TimeField(blank=True, null=True)
    email = models.EmailField(max_length=70,blank=True, null= True)
    especialidad = models.ForeignKey(Especialidad, related_name='especialidad', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_paciente

apps/Paciente/views.py
from django.shortcuts import render
from apps.Secretaria.models import CitaMedica
from apps.Secretaria.forms import CitaMedicaForm
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db import connection
from django.http import JsonResponse
import json

# Create your views here.
class Agregar_cita(CreateView): 
    #CitaMedica.objects.create(name='test')
    model = CitaMedica 
    form_class = CitaMedicaForm
    template_name = 'Paciente/hora_form.html' 
    success_url = reverse_lazy('agregar_cita_paciente')

def get_horas_no_disponibles(request):
    fecha_cita = request.GET.get('fecha_cita', None)
    rut_medico = request.GET.get('rut_medico', None)
    query = "select strftime('%H:%M', hora_cita) as 'hora_desde', strftime('%H:%M', time(hora_cita,'+45 minutes')) as 'hora_hasta' from Secretaria_citamedica where fecha_cita = '"+fecha_cita+"' and medico_id='"+rut_medico+"' order by hora_cita asc;"
    with connection.cursor() as cursor:
        cursor.execute(query)
        return JsonResponse(json.dumps(cursor.fetchall()), safe=False)

apps/Paciente/templates/Paciente/hora_form.html
{% extends 'base.html' %} 
{% load static %} 
<!--Main Header-->
{% block main%}

<!--End Main Header -->

<!--Page Title-->
<section class="page-title text-center" style="background-image:url( {% static 'images/background/3.jpg' %});">
    <div class="container">
        <div class="title-text">
            <h1>Agenda tu hora</h1>
            <ul class="title-menu clearfix">
                <li>
                    <a href="index.html">Inicio &nbsp;/</a>
                </li>
                <li>Agenda tu hora</li>
            </ul>
        </div>
    </div>
</section>
<!--End Page Title-->
{% endblock %}

{% block javascript %}
  <script>   

    $(document).ready(function()
    {
        $('#id_nombre_paciente').val("{{request.user.first_name}}");
        $('#id_email').val("{{request.user.email}}");
    });

	function soloTeclasRut(tecla) {
		return tecla.keyCode == 48 ||
		tecla.keyCode == 49 ||
		tecla.keyCode == 50 ||
		tecla.keyCode == 51 ||
		tecla.keyCode == 52 ||
		tecla.keyCode == 53 ||
		tecla.keyCode == 54 ||
		tecla.keyCode == 55 ||
		tecla.keyCode == 56 ||
		tecla.keyCode == 57 ||
        tecla.keyCode == 107 ||
		tecla.keyCode == 75;   
	}

    function noFestivos(date) {
        return jQuery.datepicker.noWeekends(date);
    }

    function removerDisabled() {
        $('#id_medico').removeAttr("disabled");
    }

    $(function() {
        $("#id_run").rut().on('rutValido', function(e, rut, dv) {
        }, { minimumLength: 7,  maximumLength: 9} );
    })

    $( function() {
        $('#id_hora_cita').timepicker({
            'timeFormat': 'H:i',
            'step': '45',
            'minTime': '8:00',
            'maxTime': '18:00',
            'disableTextInput': true
        } );
    } );
    
    $( function() {
        $( "#id_fecha_cita" ).datepicker(
            {
                'dateFormat': 'yy-mm-dd',
                'minDate': 0,
                'beforeShowDay': noFestivos
            }
        );
    } );

    $("#id_especialidad").change(function () {
      var id_especialidad = $(this).val();

      $.ajax({
        url: '/especialidad/get_especialidades',
        data: {
          'id_especialidad': id_especialidad
        },
        dataType: 'json',
        success: function (data) {
            // obtengo el elemento select (lista desplegable de medicos)
            var select = document.getElementById('id_medico');
            // le quito la cualidad de deshabilitado
            select.removeAttribute("disabled");
            // borro todos sus elementos para agregar los médicos de la especialidad consultada
            select.length = 0;
            // convierto la respuesta de medicos a json
            var dataMedicos = jQuery.parseJSON(data)
            // recorro cada uno de los médicos obtenidos para agregarlos como opción en el select
            dataMedicos.forEach(function(value) {
              // creo una opción de select
              var opt = document.createElement('option');
              // agrego el nombre de la opción, en este caso el nombre del médico
              opt.innerHTML = value.fields.nombre_medico;
              // agrego como valor de opción la pk del médico (importante para luego hacer el insert)
              opt.value = value.pk;
              // agrego la opción creada al select de médicos
              select.appendChild(opt);
            });
        }
      });
    });

    $("#id_fecha_cita").change(function () {
      var in_fecha_cita = $(this).val();
      var rut_medico = $("#id_medico").val();

      $.ajax({
        url: '/especialidad/get_horas_no_disponibles',
        data: {
          'fecha_cita': in_fecha_cita,
          'rut_medico': rut_medico
        },
        dataType: 'json',
        success: function (data) {
            var horasNoDisponibles = jQuery.parseJSON(data);
            $('#id_hora_cita').timepicker('option', 'disableTimeRanges', horasNoDisponibles);
        }
      });
    });

  </script>
{% endblock %}

{% block content %}
<!-- Contact Section -->
<section class="blog-section section style-three pb-0">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="contact-area style-two">
                    <div class="section-title">
                        <h3>Agenda tu hora médica</h3>
                    </div>
                    <form name="contact_form" class="default-form contact-form" action="" method="post">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                <form method="POST" name="hora_form" id="hora_form">
                                    {% csrf_token %} 
                                    {{ form.as_p }}
                                    <br>
                                    <button type="submit" onclick="removerDisabled();" class="btn-style-one">Reservar hora</button>
                                </form>
                                </div>                       
                            </div>
                        </div>
                    </form>
                </div>                      
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="appointment-image-holder">
                    <figure>
                        <img src="{% static 'images/background/appoinment.jpg' %}" alt="Appointment">
                    </figure>
                </div>                       
            </div>
        </div>                    
    </div>
</section>
<!-- End Contact Section -->
{% endblock %}

apps/Paciente/templates/Paciente/infocita.html
{% extends 'base.html' %} 
{% load static %} 
<h6>La información de su cita ha sido enviada a su correo</h6>
{% comment %} mostrar info de la cita aquí {% endcomment %}
{% block content %}

{% endblock%}